### ISSUE TITLE
Having trouble adding a new schema

### ISSUE THREAD

**Issue by mkutter72** [ga-wdi-boston/express-group-project#11]
I created a separate express project to test create survey,  it worked.  I'm merging that into Saad project and it's not working:

/Users/mkutter/WebProjects/Project3/project3-backend/node_modules/mongoose/lib/index.js:335
      throw new mongoose.Error.MissingSchemaError(name);
      ^
MissingSchemaError: Schema hasn't been registered for model "Survey".
Use mongoose.model(name, schema)

**Comment by srhoulam** [comment]
The issue was that you had not registered your schema with Mongoose to create a model.
