### ISSUE TITLE
Need review for CRUD controller for Survey

### ISSUE THREAD

**Issue by LaurisaNeuwirth** [ga-wdi-boston/express-group-project#13]
I am using the controller code from Antony's Express CRUD lesson. I just need to review some of it as I am starting to refactor it for our Survey App. Just need a quick few minutes please. I have reread the Express with Controllers lesson and

**Comment by LaurisaNeuwirth** [comment]
... and Expressjs.com

**Comment by srhoulam** [comment]
What exactly do you need to review?

**Comment by gaand** [comment]
Does your group still need assistance with this issue?

**Comment by LaurisaNeuwirth** [comment]
Yes! We are just leaving now so if you would see us first thing tomorrow, that would be great!

**Comment by jrhorn424** [comment]
@gaand Ben has reached out about a modeling issue. I suspect #17 is involved as well.

**Comment by LaurisaNeuwirth** [comment]
We restructured our data model as a result of this talk.
