### ISSUE TITLE
Can't manipulate Req.body in post requests

### ISSUE THREAD

**Issue by cwcrane** [ga-wdi-boston/express-group-project#15]
Having trouble getting req.body to show in our controller, when sending a post request.  

When we send over the post with a header of content-type json, we get an error from express. If we leave out the json header, we can see re.body but it is in format application/x-www-form-urlencoded

...which is not usable unless we can convert it to json somehow.

**Comment by srhoulam** [comment]
Are you using body-parsing middleware?

**Comment by cwcrane** [comment]
We added the body parser son middleware and it worked
