### ISSUE TITLE
Need guidance with our poll model schema — are child references a good solution?

### ISSUE THREAD

**Issue by resource11** [ga-wdi-boston/express-group-project#17]
This is tied to our current CRUD issue in the queue.

So… we have this schema for our poll app and need some guidance. Presently, there are two suggestion options for handling poll choices and votes. One option is listed below, the other is using child references in our schema.

Upon reading this reference material (https://docs.mongodb.org/manual/tutorial/model-tree-structures-with-child-references/) Laurisa noticed this one paragraph which has given us pause for consideration:

**The Child References pattern provides a suitable solution to tree storage *as long as no operations on subtrees are necessary*. This pattern may also provide a suitable solution for storing graphs where a node may have multiple parents.**

Considering we will be counting votes for each poll response choice, is it an unwise move to use child references in this scenario? 

We’d love to know the pros and cons so we can lock on a structure and get our CRUD actions going!

Our pollSchema:

var pollSchema = new mongoose.Schema({
  title: {
    type: String,
    required: true
  },
  choices: [ ],
  votes: [ ],
  pollURL: {
    type: String,
    required: true
  },
  owner_id: String
});

**Comment by jrhorn424** [comment]
Child references are embedding child document IDs. Instead, what you want is a serialized child collection.

**Comment by jrhorn424** [comment]
@gaand Ben has reached out about a modeling issue. They've received conflicting advice and would like you to be the tiebreaker.

**Comment by resource11** [comment]
We have restructure our models to be more scalable. Thanks for your help, @gaand and @jrhorn424 .
