### ISSUE TITLE
Error updating cart/profile 

### ISSUE THREAD

**Issue by sarabrentmccoy** [ga-wdi-boston/express-group-project#18]
Group: Sarabrent, Meng, Dave (berners_lee, e-commerce)

Error message tells us the Order validation for our POST method failed. It's a 500 error. 
We aren't finding our server messages to be helpful. We've spent 30 minutes on this. 

For the GET method, the currentProfileId is used, and that method works. 
But when we try to use it similarly in the POST method, it doesn't work. 

Here's our code in the controller 
```
post : function(req, res, next) {
            var currentProfileId;
            Profile.find({user_ObjectId: req.user._id}).exec().then(function(profile) {
                currentProfileId = profile[0]._id;
            });
            ;
            var pOrder = new Promise(function(res, rej) {
                Order.create({
                    profile_ObjectId : currentProfileId,
                    product_ObjectId : req.body.product_ObjectId
                }, function(err, order) {
                    if(err) {
                        rej(err);
                        return;
                    }
                    res(order);
                });
            });
            pOrder.then(function() {
                res.sendStatus(200);
                res.send('Created');
                return this.save();
            }).catch(function(err) {
                next(err);
            });
        }
```

and here it is in the Order schema:  
```
'use strict'

var mongoose = require('mongoose');

var orderSchema = new mongoose.Schema({
  product_ObjectId: {
    type: Array,
    required: true
  },
  profile_ObjectId: {
    type: String,
    required: true
  }
});

module.exports = orderSchema;
```

What's missing?

**Comment by sarabrentmccoy** [comment]
Weird scope issue?

**Comment by sarabrentmccoy** [comment]
(We're getting rid of the order collection)

**Comment by jrhorn424** [comment]
I'm reopening because I think an order collection may be a good idea. I'll defer to someone else as to implementation.

**Comment by srhoulam** [comment]
Mongoose is a bit clever with attribute types. Replace `profile_ObjectId`'s type with `mongoose.Types.ObjectId`, and `product_ObjectId`'s type with `[mongoose.Types.ObjectId]`.

**Comment by sarabrentmccoy** [comment]
Can each order just exist as an array of products in a profile document in the profile collection?

**Comment by sarabrentmccoy** [comment]
Right now, we have orders as an array of arrays in each profile document (and each order is an array of products)

**Comment by srhoulam** [comment]
In your POST handler for your route, you assign a single ObjectId to what should be an array of ObjectIds. That should cause mongoose to throw a validation error.

**Comment by srhoulam** [comment]
I had you rollback the change that made their models nested. Your schemas now have ObjectId attributes that reference the documents in other collections. Also your controller actions now no longer contain race conditions that correct operation and no longer leak user data across requests through global variables.
