### ISSUE TITLE
Testing Schema in Database

### ISSUE THREAD

**Issue by LaurenGrant** [ga-wdi-boston/express-group-project#2]
We are requiring our schemas in our model file when we are testing out script files and are getting an error. The two files are not connecting properly and everything our squad has looked up is not working. We have tried to test this in mongo-crud and in node.

**Comment by gaand** [comment]
What's the error?  Please paste it as a code block (triple back-ticks before and after).

**Comment by LaurenGrant** [comment]
Hi Antony, it's Rachel. We're having some real basic issues understanding how to test these things. We've spent several hours yesterday and today trying to figure this out. We're getting closer to the right track, but I don't think it's about an individual error, it's a lack of basic understanding of how to test schema.

**Comment by raq929** [comment]
Error: getaddrinfo ENOTFOUND mongodb mongodb:27017
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)

**Comment by gaand** [comment]
Is mongodb running?  What's the url?

**Comment by srhoulam** [comment]
Mongo was running, but with the wrong URL.

**Comment by srhoulam** [comment]
For future reference, here are the parts of a URL:

`protocol://hostname[:port]/path`

For mongodb urls, the protocol is `mongodb`, the hostname is the host where the database is hosted (if it is hosted on your computer, then the host is `localhost`), you don't need to specify port (and can leave the colon preceding it out), and the path is the name of your database in mongo.

**Comment by srhoulam** [comment]
They are now working with the script from Antony's mongoose lesson as a starting point.
