### ISSUE TITLE
Authentication woes

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/express-group-project#21]
Hi, we are trying to figure out how to write a route that only works if the user is authenticated (and how to see which user is authenticated). 
We've read this: http://toon.io/understanding-passportjs-authentication-flow/
and the passport documentation, but I don't really understand how sessions work.

**Comment by gaand** [comment]
Are you using Saad's code from the express-passport lesson?

**Comment by srhoulam** [comment]
You want the `req.isAuthenticated` convenience method passport gives you. It'll return a boolean reflecting whether a user is authenticated. You can access the user object in `req.user` for specific user details.
