### ISSUE TITLE
Testing an issue where a user who is not the author delete's a blog

### ISSUE THREAD

**Issue by gracenjambi** [ga-wdi-boston/express-group-project#22]
Use case: We want to make sure that: When not an author of a blog the blog cannot be deleted. 

When we test in Postman,  the code works but does not provide the appropriate response. The response looks like the blog has been deleted, but when we view all blogs the blog is still present as it should be.

We have done research online for over an hour but have not been able to come up with a solution.

Below is our code:

Blog.findOneAndRemove({_id : req.params.id, author: req.user.userName}, function(error){
   if (error){
     console.error("You are not authorized to delete")
   }
 })
 },

**Comment by srhoulam** [comment]
The code you've pasted is out of context. Please put it in context and surround it with triple backticks so it's readable.

**Comment by gracenjambi** [comment]
We have been able to figure out the issue. We shifted where we were using the return and 401 http error and it worked.
