### ISSUE TITLE
Trouble adding values to an array with node

### ISSUE THREAD

**Issue by baz1389** [ga-wdi-boston/express-group-project#23]
We are testing out our Create functionality in node/mongoose on the command line and are having trouble inputting multiple items into the array. Currently, a specific poll can have one option as an answer. In the case below, we are trying to figure out how we can have more than the value of "Ben" in the option array.

```
{
	"_id" : ObjectId("565dd5e5db24e4a0251f0054"),
	"title" : "Whats your name?",
	"owner_id" : "349853453",
	"options" : [
		"Ben"
	],
	"__v" : 0
}
> 
```

**Comment by gaand** [comment]
Is this create or update?

**Comment by baz1389** [comment]
This is for create. We just got update to work by updating the title value.

**Comment by tdyer** [comment]
Is there an error being thrown when you add another value to the options array?

**Comment by tdyer** [comment]
Had a problem converting a string of names to an array of name. 

"Joe,   Jill,  Alice".split(',').map(function(name){ return name.trim(); }  // will return an array of names.
