### ISSUE TITLE
Patch Route

### ISSUE THREAD

**Issue by drewster317** [ga-wdi-boston/express-group-project#26]
Having trouble creating a new route for PATCH. We are in the classroom. Mike, Leah, and Drew.

**Comment by srhoulam** [comment]
Can you give more details?

**Comment by drewster317** [comment]
We added a new entry to module exports and we added a corresponding PATCH item to the routes file. The new item in the module export is undefined.

**Comment by srhoulam** [comment]
It's likely that you've got a typo in your reference to it in your routes.
