### ISSUE TITLE
Patch Controller Issue

### ISSUE THREAD

**Issue by LaurenGrant** [ga-wdi-boston/express-group-project#27]
We are making a patch request on our blog posts and it is going through with a 200 status and updates the specific blog post in our DB. The problem I am seeing is that the updated fields are passed in null instead of the new string we entered in. 

Our squad has been working on this for a while and google has not shown up any additional resources.

**Comment by gaand** [comment]
Please post the ajax and controller code.

**Comment by LaurenGrant** [comment]
Hi Antony - no ajax code, we are testing in Postman. Here is the controller code
```
  updatePost : function(req, res, next) {
    var postFindPromise = new Promise(
      function(resolve, reject) {
      var selectedPost =  Post.findById(req.params.id, function(error, Post){
      if (error) {
        reject(error);
      }
      resolve(selectedPost);
      });
    });

    var postUpdatePromise = function(selectedPost) {
      selectedPost.update({
        title: req.body.title,
        entry: req.body.entry
      }, function(error, Post){
        if(error) {
          return;
      }
      res.json(Post);
      });
    };

    postFindPromise.then(
    postUpdatePromise).catch(function(error) {
      res.send('Invalid Entry. Please Try Updating Your Post Again.');
    });
  },
```

**Comment by raq929** [comment]
We moved on to delete, and we're having a similar issue. We get a status code 200, even though we're not sending one, and it's not deleting, or sending the info we asked it to send back. =/

**Comment by gaand** [comment]
I believe that you want to call exec on the return from findById and then use that promise rather than creating your own.

**Comment by raq929** [comment]
So, we fixed it so that it IS updating, but it's updating with null instead of what we want it to update with. Calling res.body.title worked well for create, and we don't understand why it's not working here.

**Comment by gaand** [comment]
How did you change the code?  Did you use the mongoose returned promise?

**Comment by raq929** [comment]
No, we used our promises. It turned out that we didn't have the correct headers telling the server we were sending json. :P

**Comment by gaand** [comment]
I think using the mongoose promise as the start of a promise chain would make your code mode comprehensible.

**Comment by raq929** [comment]
Yeah, we will refactor if we have time. (Can you close this issue? I can't because I didn't create it.)

**Comment by gaand** [comment]
Sure.
