### ISSUE TITLE
Trouble retrieving user name from back end.

### ISSUE THREAD

**Issue by HoldenMills** [ga-wdi-boston/express-group-project#28]
We are trying to show a username as a greeting at the top of the page after a user logs in.  We changed the route to access our authentication controller  Our root auth Controller now reads;

get : function(req, res) {
            console.log(req.user);
            res.json({
                title : (req.user && req.user.userName) || 'Nobody'

We didn't change any of the models.  After submitting the form where the user enters the username, we run a call back 'loginCB'. Within that callback is a getUserCB which console.logs the data.  The console on Chrome shows the name to be "nobody" which is an error message, but the user is definitely logged in.  We are trying to get the username from the back end because we thought it would be a more reliable way then grabbing it from the user input.

**Comment by gaand** [comment]
Does the the console log in express also show `'Nobody'`?

**Comment by srhoulam** [comment]
Do your AJAX requests have the `xhrOptions.withCredentials` option set to `true`?

**Comment by cwcrane** [comment]
@gaand  yes
@srhoulam yes

**Comment by srhoulam** [comment]
What is the current status of this issue?

**Comment by cwcrane** [comment]
unresolved
