### ISSUE TITLE
need help with integration architectural advices

### ISSUE THREAD

**Issue by leahphuong** [ga-wdi-boston/express-group-project#29]
We have generated the random url for the survey taker, when they click on it, it returns the json information for the survey but we don't know how to manage creating the web form.

**Comment by gaand** [comment]
Look at `location` in the browser and using hash paths for single page apps, e.g. http://localhost:5000/#survey-123abc456def789ghi.

**Comment by srhoulam** [comment]
Here's [another piece](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onhashchange) you'll need for this puzzle.

**Comment by gaand** [comment]
You may not have to implement the onhashchange event, but it would be cool.

**Comment by gaand** [comment]
In jquery, `$(window).on('hashchange', function(event) {...});`

**Comment by gaand** [comment]
You will have to check the value of the hash on page load.

**Comment by leahphuong** [comment]
I'm still super confused with this. Could you walk me through please?

**Comment by gaand** [comment]
Did you try the jquery code above?  You can add `#this-is-the-hash` to the end of the front end url, hit return, then check the value using `location`.

**Comment by leahphuong** [comment]
we used location.search and it worked!!!
Thank you Antony, Saad!!
