### ISSUE TITLE
Git Pull

### ISSUE THREAD

**Issue by wiltrahan** [ga-wdi-boston/express-group-project#30]
I ran 'git pull origin blwindow' and got; CONFLICT (content): Merge conflict in index.html
Failed to merge in the changes.  It then knocked me off the 'blwindow' branch, I ran a git status and got; rebase in progress; onto bb73702 You are currently rebasing branch 'blwindow' on 'bb73702'.

Our branch then got behind the remote, but we hadn't made any other commits.  We can't figure out how to get this fixed.

**Comment by gaand** [comment]
You have to resolve the conflicts and continue the rebase (or abort the rebase).

`git status` should say something like that.

**Comment by wiltrahan** [comment]
Got it fixed...thank you.
