### ISSUE TITLE
Trying to test uploads

### ISSUE THREAD

**Issue by kaylal12** [ga-wdi-boston/express-group-project#32]
Group: Jeff, Edie, Kayla

We were trying to figure out how to test uploading files in postman but are unable to read the property.
When using content-type application/json, we get an error saying that it is invalid json (because it's an image file?)
When trying to use content-type image/jpg, we get an error saying that it cannot read property.

We try to upload the file using the binary tab in body.

Is there another way to test uploading without connecting to the front end? Are we missing something in postman?

**Comment by jcmeyer10** [comment]
Even if we had the CLI commands that would be super helpful.  We just need to confirm we can upload a file and upload a file to AWS before we can move on to the next task.

**Comment by gaand** [comment]
It looks like you might have used the `solution` branch rather than the `promises` branch as a template.  That is probably a source of trouble.

**Comment by jcmeyer10** [comment]
An update, I just got this error after changing templates from solution to promises.  I was trying everything and switched over the user a w s stuff but doubt that had anything to do with it.  Seems like this is an amazon thing since there is no usual stack trace error log

```javascript
~/WDI/packrat/packRat-backend2 (jm-working)$ node bin/aws-upload-cli.js "five.jpg" "hello"
{ [MissingRequiredParameter: Missing required key 'Bucket' in params]
  message: 'Missing required key \'Bucket\' in params',
  code: 'MissingRequiredParameter',
  time: Tue Dec 01 2015 21:57:50 GMT-0500 (EST) }

**Comment by jcmeyer10** [comment]
changed the var bucket to process.env.AWS_BUCKET (from AWS_S3_BUCKET) to match up to our file, and then got this error in the console.  IIRC in the multer lesson, this was a milestone of sorts where we should have been.  I had to change the user key and secret in aws but updated them in the .env file to reflect new keys.

```javascript
~/WDI/packrat/packRat-backend2 (jm-working)$ node bin/aws-upload-cli.js "five.jpg" "hello"
{ [AccessDenied: Access Denied]
  message: 'Access Denied',
  code: 'AccessDenied',
  region: null,
  time: Tue Dec 01 2015 22:32:57 GMT-0500 (EST),
  requestId: '48343BCA4DEA65B1',
  extendedRequestId: 'jm22aULx9dgCzEkQ4MuU5fpD+lHgwGZIioDsbm1NTaw8hXjT9B4TH7xxRZRm7gB5Tvz1dsNvp+Q=',
  statusCode: 403,
  retryable: false,
  retryDelay: 30 }

**Comment by jcmeyer10** [comment]
At least have the upload to AWS part figured out, will need help in the AM reflecting this in our MongoDB

```javascript
~/WDI/packrat/packRat-backend2 (jm-working)$ node bin/aws-upload-cli.js "five.jpg" "hello"
{ _id: 565e6d63a9f324f7758c5696,
  caption: 'hello',
  mime: 'image/jpeg',
  url: 'https://midden-wd-09.s3.amazonaws.com/2015-12-02/c252bd24f38d384ecc3db457b421b6d6.jpg',
  __v: 0 }

**Comment by jcmeyer10** [comment]
It seems like everything is syncing up.
<img width="1280" alt="screen shot 2015-12-01 at 11 33 15 pm" src="https://cloud.githubusercontent.com/assets/12531471/11522342/2c39ffdc-9884-11e5-83bc-0d764ec88b88.png">

**Comment by gaand** [comment]
Glad to see you worked it out!

If this issue is resolved, would you please close it?  Thanks.
