### ISSUE TITLE
cant do a push in my app

### ISSUE THREAD

**Issue by mkutter72** [ga-wdi-boston/express-group-project#34]
Trying to use a mongo push command within a patch and am getting the following error;
PATCH /result/update 500 4.946 ms - 2
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)

**Comment by MattB-GA-Boston** [comment]
Mike, given the Error (`ServerResponse`), I am inclined to believe that this is an Express issue. Have you looked over your controller as a potential source of error?

**Comment by mkutter72** [comment]
Antony helped me solve it.  Incorrect use of promises

**Comment by mkutter72** [comment]
Antony helped me solve it.  Incorrect use of promises
