### ISSUE TITLE
Storing data from a promise

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/express-group-project#38]
Ok, so I have a promise that returns all of the pages that a user owns. I want to return that data and some user data (and later post data) as json.
So, I want to store the results of my pages promise in a variable, but I'm having trouble doing that. Trying to return the result at the end doesn't seem to work, and trying to store the result as a side effect is... not effective. HALP!

**Comment by gaand** [comment]
Promises don't return data.  They pass it as an arguemnt to functions passed to `then`.

**Comment by raq929** [comment]
Right. But I want data. I tried to get the function passed to then to return data, but I can't. Is there no way to get at that data other than sending as an http response?

**Comment by raq929** [comment]
I'm trying to build a json response based on several find queries on the database.

**Comment by raq929** [comment]
If i can console log the data, why can't I assign it to a variable that is outside of the promise chain?

**Comment by gaand** [comment]
You can pass result along the promise chain (using an array or object).

**Comment by gaand** [comment]
Because the code isn't executing in the order you think it is.

**Comment by raq929** [comment]
OK. So is there no way to store it outside the chain at all? 
I'm confused.

**Comment by gaand** [comment]
```js
var postsPromise = Post.find(...).exec();
var pagesPromise = Page.find(...).exec();

Promise.all([postsPromise, pagesPromise]).
  then(function(results) {
    var posts = results[0];
    var pages = results[1];
    var responseJSON = {posts, pages};

    res.json(responseJSON);
  }).catch(function(error) {
    next(error);
  });
```
