### ISSUE TITLE
Server slowdown

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/express-group-project#39]
My backend server suddenly started going really slowly. I have restarted it many times, but it is still SUPER slow. Except when it's not. D:

**Comment by raq929** [comment]
This may be related to the previous issue. I'm concerned that we may not be actually closing the db after querying it.

**Comment by gaand** [comment]
If you stop and restart the server (Ctrl-C) then the database resources should be freed.  Mongo might stil be doing something, but only for a short time (seconds?).

So, if it's still slow after a restart, it might be something else.

**Comment by raq929** [comment]
It seems to have fixed itself? Mostly? I'll reopen if it persists.
