### ISSUE TITLE
Getting persistent error on authentication/server connect not working

### ISSUE THREAD

**Issue by LaurisaNeuwirth** [ga-wdi-boston/express-group-project#4]
We have been working as a group & checked our files against the Express Passport lesson and we don't see any differences between our files. We have tested in Postman and need some help to see where the connection isn't working, please.

**Comment by srhoulam** [comment]
Do you get any error messages?

**Comment by LaurisaNeuwirth** [comment]
Yes an error on user authentication in postman but we closed that already. Do you need to see the error msg first?

**Comment by baz1389** [comment]
```
{"message":"User validation failed","error":"ValidationError: User validation failed\n at MongooseError.ValidationError (/Users/benjaminspencer/WDI/surveyProject/survey-back-end/node_modules/mongoose/lib/error/validation.js:23:11)\n at model.Document.invalidate (/Users/benjaminspencer/WDI/surveyProject/survey-back-end/node_modules/mongoose/lib/document.js:1280:32)\n at /Users/benjaminspencer/WDI/surveyProject/survey-back-end/node_modules/mongoose/lib/document.js:1155:16\n at validate (/Users/benjaminspencer/WDI/surveyProject/survey-back-end/node_modules/mongoose/lib/schematype.js:662:7)\n at /Users/benjaminspencer/WDI/surveyProject/survey-back-end/node_modules/mongoose/lib/schematype.js:690:11\n at Query. (/Users/benjaminspencer/WDI/surveyProject/survey-back-end/node_modules/mongoose-unique-validator/index.js:54:29)\n at /Users/benjaminspencer/WDI/surveyProject/survey-back-end/node_modules/kareem/index.js:177:19\n at /Users/benjaminspencer/WDI/surveyProject/survey-back-end/node_modules/kareem/index.js:109:16\n at doNTCallback0 (node.js:419:9)\n at process._tickCallback (node.js:348:13)"}
```

**Comment by baz1389** [comment]
{"message":"User validation failed","error":"ValidationError: User validation failed\n at MongooseError.ValidationError (/Users/benjaminspencer/WDI/surveyProject/survey-back-end/node_modules/mongoose/lib/error/validation.js:23:11)\n at model.Document.invalidate (/Users/benjaminspencer/WDI/surveyProject/survey-back-end/node_modules/mongoose/lib/document.js:1280:32)\n at /Users/benjaminspencer/WDI/surveyProject/survey-back-end/node_modules/mongoose/lib/document.js:1155:16\n at validate (/Users/benjaminspencer/WDI/surveyProject/survey-back-end/node_modules/mongoose/lib/schematype.js:662:7)\n at /Users/benjaminspencer/WDI/surveyProject/survey-back-end/node_modules/mongoose/lib/schematype.js:690:11\n at Query. (/Users/benjaminspencer/WDI/surveyProject/survey-back-end/node_modules/mongoose-unique-validator/index.js:54:29)\n at /Users/benjaminspencer/WDI/surveyProject/survey-back-end/node_modules/kareem/index.js:177:19\n at /Users/benjaminspencer/WDI/surveyProject/survey-back-end/node_modules/kareem/index.js:109:16\n at doNTCallback0 (node.js:419:9)\n at process._tickCallback (node.js:348:13)"}

**Comment by srhoulam** [comment]
It looks like you're trying to create a new user with an already-taken username.

**Comment by LaurisaNeuwirth** [comment]
Saad what did you read in the error that indicated that?

**Comment by LaurisaNeuwirth** [comment]
That did not solve our problem yet. Can you look at this with us?

**Comment by srhoulam** [comment]
I'll come check it out.

**Comment by srhoulam** [comment]
Your authentication works.
