### ISSUE TITLE
problem with registration and/or login access

### ISSUE THREAD

**Issue by bbarbersox** [ga-wdi-boston/express-group-project#40]
Getting the following error message when registering or logging in from front end to back end server.  Have a .env file and cors seems to be installed.  Other squad members are not getting this error.

XMLHttpRequest cannot load http://localhost:3000/login. The 'Access-Control-Allow-Origin' header has a value 'http://localhost:5000' that is not equal to the supplied origin. Origin 'null' is therefore not allowed access.

**Comment by bbarbersox** [comment]
Have run npm install cors --save that was refereferneced in a prior issue.  But am still having the same issue.

**Comment by raq929** [comment]
Bill has pulled from development on both the frontend and the backend. 
Registration and login work on my machine when running servers on development.

**Comment by gaand** [comment]
Likely using `file:///...` to open the front end instead of `http://localhost:5000`.

**Comment by bbarbersox** [comment]
Thank you.
