### ISSUE TITLE
Help writing Mongoose query using _id (back end)

### ISSUE THREAD

**Issue by dhuddell** [ga-wdi-boston/express-group-project#41]
We want to pass objects (ListItems) to the front end referencing their mongo ID which is saved in User.
This is our User objects, which contains list, which is an array of ListItem IDs.
```
{
  "title": {
    "_id": "565e0904eb8f76255c362e68",
    "userName": "a@a",
    "__v": 2,
    "passwordDigest": "$2a$16$vQhBjk7b8XLYv.5D9eslm.TVcPDiFKmfVez1jxu1U1G1sUne51/Oq",
    "list": [
      "565f1c1f7eba031810ae2399",
      "565f1c257eba031810ae239a"
    ]
  }
}
```
The listItem looks like this: 
`{ "_id" : ObjectId("565f1c257eba031810ae239a"), "name" : "Test2", "city" : "Place2t", "__v" : 0 }`

I'm trying to write this into an array which I'm going pass into the Front end as JSON. 
```

    showList : function(req, res) {
        if(!req.user) {
            var err = new Error("Not Authorized!");
            return next(err);
        }
        console.log(req.user.list);
        var itemArray = req.user.list.forEach(ref){
            // Unsure ??
        }
        res.json({
            title : (itemArray) || 'No List.'
        });

    },
```

**Comment by dhuddell** [comment]
I was working inside mongo using db.listitems.find( { _id: <example id> } ) but I'm having trouble getting the right syntax into Mongoose.

**Comment by gaand** [comment]
Have a look at populate to see if it's what you want:
http://mongoosejs.com/docs/api.html#query_Query-populate
http://mongoosejs.com/docs/populate.html

**Comment by dhuddell** [comment]
I just realized as I was on the Mongoose docs this is likely what I want, built in. Go figure. Will close if I get this. Thank you.

**Comment by dhuddell** [comment]
Can I get help on writing populate? I've been digging into this for a bit now.

**Comment by gaand** [comment]
Sure.  Give me a few minutes.

**Comment by dhuddell** [comment]
Fixed by altering the square brackets in the schema: 
```
var userSchema = new Schema({
	userName : {
		type : String,
		unique : true,
		required : true
	},
	passwordDigest : String,
	list : [{
		type: Schema.Types.ObjectId,
		ref: "ListItem"
	}]
});
```
