### ISSUE TITLE
Back-end CRUD help

### ISSUE THREAD

**Issue by baz1389** [ga-wdi-boston/express-group-project#42]
We have successfully tested CUD on the back end for polls (still need R) and CR for pollAnswers (which is all we need for that model) through command line scripts. Struggling with how to turn that into cod that functions with the front end.

**Comment by gaand** [comment]
Are you able to send the JSON for the things you've created in the api to the client?

**Comment by baz1389** [comment]
We are not able to.

**Comment by baz1389** [comment]
But we are also stuck on getting read to work on the back end so we need to solve that before testing and sending data to the client

**Comment by tdyer** [comment]
Working on it now. Problem with controllers.

**Comment by tdyer** [comment]
Multiple problems, most recent was trying to create a Poll with curl. They are working out the how to POST a JSON Array with curl.
