### ISSUE TITLE
LogMeIn

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/express-group-project#44]
Ok, so. I am trying to log in from our homepage. I can login from Postman. When I login from the homepage, I get "nobody". 
I am on development on frontend and backend. Lauren is having a similar error. 
Bill, on the same branches, is NOT getting the error.

**Comment by gaand** [comment]
Did you al try with the same user?

**Comment by raq929** [comment]
We don't have a central database, so we all have different users.

**Comment by srhoulam** [comment]
Are you setting `xhrFields.withCredentials` in your AJAX options?

**Comment by gaand** [comment]
Right (databases unshared).  So, you're all using the same branch without any local changes?  (Mostly asking about changes on Bill's machine, but any differences could be a culprit).

**Comment by raq929** [comment]
Bill and Lauren's machines are ahead of where mine is. 
(This was working for all of us. This was working for me about 5 minutes before it stopped working for me. We haven't been working on my machine. So.... It's very confusing.)

**Comment by raq929** [comment]
@srhoulam yes.

**Comment by gaand** [comment]
Any error messages?  API or client?

**Comment by raq929** [comment]
Nope. I mean, the api is sending back 302, like it does when you are not a user. Postman logs us in as expected.

**Comment by srhoulam** [comment]
Have you checked your AJAX requests in the network tab of development tools? Every request after logging in should have a cookie header.

**Comment by raq929** [comment]
We're not successfully logging in. 
We actually just figured out that Bill is not successfully logging in either. But instead of logging the error, it continues through our login callback. Bill is not getting the 'nobody' message.

**Comment by raq929** [comment]
This was working this morning, and I have looked through our commits and can't find the issue. We're pretty stuck; this is preventing us from moving forward.

**Comment by srhoulam** [comment]
Is your login request sending login credentials? Copy/paste the request payload here.

**Comment by raq929** [comment]
Yes. Can we get someone to come to us? We've been working on this for about two hours.

`username=Rachel24&password=1`

**Comment by raq929** [comment]
Accept:application/json, text/javascript, */*; q=0.01
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.8
Cache-Control:no-cache
Connection:keep-alive
Content-Length:25
Content-Type:application/x-www-form-urlencoded; charset=UTF-8
Host:localhost:3000
Origin:http://localhost:5000
Pragma:no-cache
Referer:http://localhost:5000/
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36
Form Data
view source
view URL encoded
username:user4
password:1

**Comment by srhoulam** [comment]
I'm out sick today, so I can't come help you in person.

So you're sending URL-encoded data. Check your app.js -- do you have a `app.use(bodyParser.urlencoded(/* ... */));` statement?

**Comment by raq929** [comment]
Yes. This was working this morning. We have not changed the encoding. As far as I know we haven't changed ANYTHING.

**Comment by srhoulam** [comment]
Can you paste the source for your AJAX request to log in?

**Comment by raq929** [comment]
```javascript
login: function (credentials, callback) {
    this.ajax({
      method: 'POST',
      // url: 'http://httpbin.org/post',
      url: this.bh + '/login',
      data: credentials,
      dataType: 'json',
      xhrFields: {
        withCredentials: true
      }
    }, callback);
  },
```

```javascript
 $('#login-form').on('submit', function(e){
    e.preventDefault();
    var data = $(this).serialize();
    bhApi.login(data, function (err, data){    
      if (err){
        console.error(err);
        return false;
      } 
      console.log("you have logged in");
      console.log(data);
      return false;
    });
  }),
```

**Comment by raq929** [comment]
It works from Postman, so I don't think it's an error on the backend, but I could be wrong.

**Comment by raq929** [comment]
```javascript
bh: 'http://localhost:3000',

  ajax: function(config, cb) {
    $.ajax(config).done(function(data, textStatus, jqxhr) {
      cb(null, data);
    }).fail(function(jqxhr, status, error) {
      cb({jqxher: jqxhr, status: status, error: error});
    });
  },
```

**Comment by srhoulam** [comment]
Remove `dataType: 'json'` from your AJAX options object in your login API call. jQuery takes it to mean that, unless it gets a JSON response back, the request failed.

**Comment by raq929** [comment]
Deleted that line, restarted the server, tried again. Still the same error. We're getting Object {title: "Nobody"}
from the server.

**Comment by srhoulam** [comment]
Okay. I just noticed you didn't confirm whether subsequent requests have cookie headers. Can you look at the server's response to your login request and confirm that there is a set-cookie header? Next, look at a request your page makes after that and check that it has a cookie header. Please answer the previous two questions separately.

**Comment by raq929** [comment]
I'm not sure what you mean.

**Comment by srhoulam** [comment]
Using the network tab of your browser's developer tools, I'd like you to inspect the headers of your AJAX requests and the server's response.

**Comment by raq929** [comment]
From the login request:
Remote Address:[::1]:3000
Request URL:http://localhost:3000/login
Request Method:POST
Status Code:302 Found
Response Headers
view source
Access-Control-Allow-Credentials:true
Access-Control-Allow-Origin:http://localhost:5000
Connection:keep-alive
Content-Length:23
Content-Type:text/plain; charset=utf-8
Date:Wed, 02 Dec 2015 20:58:42 GMT
Location:/
Vary:Origin, Accept
X-Powered-By:Express
Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.8
Cache-Control:no-cache
Connection:keep-alive
Content-Length:28
Content-Type:application/x-www-form-urlencoded; charset=UTF-8
Cookie:connect.sid=s%3Ac9744916-5af5-4537-95c1-b91868b1fff8.JKU1yuVtI3SOqorAKVSLHITKb5tZaW%2FveyLGmj7B3d8
Host:localhost:3000
Origin:http://localhost:5000
Pragma:no-cache
Referer:http://localhost:5000/
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36
Form Data
view source
view URL encoded
username:Rachel24
password:1

**Comment by raq929** [comment]
We have a subsequent request in the login callback, but it is not executing correctly.

**Comment by srhoulam** [comment]
Try replacing your login API method with this:

```
login: function (credentials, callback) {
    this.ajax({
      method: 'POST',
      // url: 'http://httpbin.org/post',
      url: this.bh + '/login',
      data: credentials,
      dataType: 'json',
      xhrFields: {
        withCredentials: true
      }
    }, function() {
        $.ajaxSetup({
            xhrFields : {
                withCredentials : true
            }
        });
        callback.apply(this, arguments);
    });
  },
```

**Comment by raq929** [comment]
Same error. 
Subsequent requests get 401 unauthorized, as they should if not logged in. Bill is sending the headers.

**Comment by bbarbersox** [comment]
Access-Control-Allow-Credentials:true
Access-Control-Allow-Origin:http://localhost:5000
Connection:keep-alive
Content-Length:12
Content-Type:text/plain; charset=utf-8
Date:Wed, 02 Dec 2015 21:12:37 GMT
ETag:W/"c-4G0bpw8TMen5oRPML4h9Pw"
set-cookie:connect.sid=s%3A1992e994-5853-484b-8d92-349e1f2e4de4.lVRSiUHv7zqElKXgjhOSR%2FZabKefKdiA%2Fm1SEP%2FAgpA; Path=/; Expires=Wed, 02 Dec 2015 21:45:57 GMT; HttpOnly
Vary:Origin
X-Powered-By:Express

**Comment by srhoulam** [comment]
Can you show me the source code of the handler for the route you're making a request to after logging in?

**Comment by raq929** [comment]
Controller
```javascript
var mongoose = require("../models/index");
var db = mongoose.connection;

var Page = require('../models/Page.js');
var Post = require('../models/Post.js');

var done = function() {
  db.close();
};

var auth = function(req, res, next){ if (!req.isAuthenticated()) res.send(401); else {return next();} };


var showPage = function(user_id) {
  Page.find({'owner': user_id})
  .exec()
  .then(function(page) {
    console.log("THIS PAGE LIST IS FOR A SINGLE USER");
    console.log(page);
    
  }).catch(function(error){
    console.error(error);
  })
};

var showPost = function(user_id) {
  Post.find({'owner': user_id})
  .exec()
  .then(function(post) {
    console.log("THIS POST LIST IS FOR A SINGLE USER");
    console.log(post);
  }).catch(function(error){
    console.error(error);
  }).then(done)
  .then(function(post){
    return post;
  });
};

// var promiseChain = Page.find({'owner': user_id})
//   .exec()
//   .then(function(pages){
//     return {pages: pages};
//   }).then(function(pagesObject){
//     pagesObject.posts = Post.find({'owner': user_id});
//     return pagesObject;
//   });




var Dashboard = {
  auth: auth,

  get: function(req, res, next){
    var userId = req.user._id;

    var pagesPromise = Page.find({'owner': userId})
    .exec();

    var postsPromise = Post.find({'owner': userId})
    .exec();
      Promise.all([pagesPromise, postsPromise]).then(function(pagesAndPostsResults) { 
        var pages = pagesAndPostsResults[0];
        var posts = pagesAndPostsResults[1];
        var sendBack = {username: req.user.userName, userId: userId,
    pages: pages, posts: posts};

    res.json(sendBack);
      }).catch(function(error){
        next (error);
      });
  }
};



module.exports = Dashboard;
```

**Comment by raq929** [comment]
Route

```javascript
var express = require('express');
var router = express.Router();
// var mongoose = require('index');
var controller = require('../controllers/dashboard');



/* GET users listing. */


router.route('/')
  .all(controller.auth)
  .get(controller.get);

module.exports = router;
```

**Comment by bbarbersox** [comment]
'use strict'

//this is what I want the final JSON to look like
//var navData = {username: "Rachel", url: "/Rachel/", 
// posts: [ { title: "My first blog", entry: "I created a blog!", date: "2015-10-15"}, {title: "Essential Biking Safety Gear", entry: "I created a blog!", date: "2015-10-15"},{blogName: "Rachel's blog", name: "My third blog", details: "I created a thing!", date: "2015-10-15"}]
// pages: [{title: "something", content:"Some content", url:"someurl/"}]
// };

var mongoose = require("../models/index");
var db = mongoose.connection;

var Page = require('../models/Page.js');
var Post = require('../models/Post.js');

var done = function() {
  db.close();
};

var auth = function(req, res, next){ if (!req.isAuthenticated()) res.send(401); else {return next();} };


var showPage = function(user_id) {
  Page.find({'owner': user_id})
  .exec()
  .then(function(page) {
    console.log("THIS PAGE LIST IS FOR A SINGLE USER");
    console.log(page);
    
  }).catch(function(error){
    console.error(error);
  })
};

var showPost = function(user_id) {
  Post.find({'owner': user_id})
  .exec()
  .then(function(post) {
    console.log("THIS POST LIST IS FOR A SINGLE USER");
    console.log(post);
  }).catch(function(error){
    console.error(error);
  }).then(done)
  .then(function(post){
    return post;
  });
};

// var promiseChain = Page.find({'owner': user_id})
//   .exec()
//   .then(function(pages){
//     return {pages: pages};
//   }).then(function(pagesObject){
//     pagesObject.posts = Post.find({'owner': user_id});
//     return pagesObject;
//   });




var Dashboard = {
  auth: auth,

  get: function(req, res, next){
    var userId = req.user._id;

    var pagesPromise = Page.find({'owner': userId})
    .exec();

    var postsPromise = Post.find({'owner': userId})
    .exec();
      Promise.all([pagesPromise, postsPromise]).then(function(pagesAndPostsResults) { 
        var pages = pagesAndPostsResults[0];
        var posts = pagesAndPostsResults[1];
        var sendBack = {username: req.user.userName, userId: userId,
    pages: pages, posts: posts};

    res.json(sendBack);
      }).catch(function(error){
        next (error);
      });
  }
};



module.exports = Dashboard;

**Comment by srhoulam** [comment]
Do not close your database connection. That makes sense in a command-line script, and not in a server. Still reading.

**Comment by raq929** [comment]
Why would this affect the login?

**Comment by srhoulam** [comment]
It shouldn't affect your login, but it will affect all subsequent requests that retrieve documents from mongo after your database connection was closed.

**Comment by srhoulam** [comment]
It looks like you're not using `showPage` and `showPost` at all. Please comment them out along iwth `done`.

**Comment by raq929** [comment]
Yeah, we refactored. Commenting it out.

**Comment by srhoulam** [comment]
Let's take a step back to basic causes. Can you register *then* login? Or otherwise confirm that the login credentials actually work before testing with them. Next, how long does your session last? My code set a max session age of 5 minutes. You may want to multiply that by at least 3.

**Comment by raq929** [comment]
We can register, but we can't login with the newly registered user. 
We can confirm that the login credentials work in Postman. 
Our sessions last for 20 minutes.

**Comment by srhoulam** [comment]
Have you altered your auth controller and auth routes to match what I slacked in the code channel on Monday? I just noticed that the status code in the server's response to your login request implies it's redirecting you.

**Comment by raq929** [comment]
It is. But that wasn't an issue before. And apparently no longer an issue. I changed nothing, and now I can login with a new user. It seems like the login is not grabbing data from the form correctly. Looking into it now.

**Comment by raq929** [comment]
OK. Now it's logging me in as the same person I log in as first every time I log in. It seems like it's grabbing the correct data from the form. Do I need to logout before being able to log in as someone else?

**Comment by srhoulam** [comment]
Yes.

**Comment by raq929** [comment]
Ok, we can now log out. But we can't login as users that were created before this issue started. We can log in as any user we created after the issue resolved itself. We have confirmed that new users are in the same database as the old ones.

**Comment by jrhorn424** [comment]
After talking with @raq929 I believe this is resolved.

**Comment by raq929** [comment]
Until it rears it's ugly head again. :)

**Comment by raq929** [comment]
Aaaaand, we're back.
Lauren and Bill are continuing to have this issue. 
Here's what happened on my end. I created a route. I tested login, no problem. I created a script. I made some posts for a user. Login failed.
I made a new user, and can login as that user, but not as any previous users.

**Comment by raq929** [comment]
Sam says: Is there a cache between the authentication and the database? Could this be a caching error? 

I feel like the answer to this is no; as we don't have any caching middleware installed, and google search leads me to believe that neither express-session nor passport is doing any caching, but I thought I'd throw it out there, because wtf this error.

**Comment by jrhorn424** [comment]
Is this related to #50?

**Comment by raq929** [comment]
throw new TypeError('Router.use() requires middleware function but got a ' + gettype(fn));
      ^

**Comment by raq929** [comment]
```
/Users/racheltstevens/GeneralAssembly/Projects/project3-back-end/node_modules/express/lib/router/index.js:458
      throw new TypeError('Router.use() requires middleware function but got a ' + gettype(fn));
      ^

TypeError: Router.use() requires middleware function but got a undefined
    at Function.use (/Users/racheltstevens/GeneralAssembly/Projects/project3-back-end/node_modules/express/lib/router/index.js:458:13)
    at EventEmitter.<anonymous> (/Users/racheltstevens/GeneralAssembly/Projects/project3-back-end/node_modules/express/lib/application.js:219:21)
    at Array.forEach (native)
    at EventEmitter.use (/Users/racheltstevens/GeneralAssembly/Projects/project3-back-end/node_modules/express/lib/application.js:216:7)
    at Object.<anonymous> (/Users/racheltstevens/GeneralAssembly/Projects/project3-back-end/app.js:66:5)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/racheltstevens/GeneralAssembly/Projects/project3-back-end/bin/www:7:11)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
```
