### ISSUE TITLE
Help making https requests to Stripe, using localhost

### ISSUE THREAD

**Issue by cwcrane** [ga-wdi-boston/express-group-project#45]
We're working on integrating stripe. We pushed our front end to gh-pages, so we could make https requests to stripe (which gets us a token). Our front end is supposed to receive that token, send it to our back end, and then our back end (on localhost:3000 currently) is supposed to send a transaction to stripe. 

The problem: now that our front-end is on gh-pages, https, it won't load anything from localhost:3000. 

Looking for some advice on how to test stripe?

**Comment by gaand** [comment]
Have a look in the code channel and let me know if that helps.

**Comment by cwcrane** [comment]
A little confused. So do you think we need to deploy our backend to heroku in order to test with stripe.

**Comment by gaand** [comment]
No, the code in slack allows the client to be served from github.io and have the javascript call the api on localhost.

**Comment by cwcrane** [comment]
Would you mind stopping back in? We have the code in place, but still getting loading issues in the client (gh-pages) with ?dev=true set in the header

**Comment by gaand** [comment]
@atsundwn:
We need to check `chrome://settings/cookies` to see if the cookie gets set.
We need to check that your chrome settings don't block third-party cookies.

**Comment by gaand** [comment]
If this issue is resolve, please close it.  Thanks.
