### ISSUE TITLE
Hosting on Heuroku

### ISSUE THREAD

**Issue by mkutter72** [ga-wdi-boston/express-group-project#46]
We will be receiving instructions on how to setup our backend on Heuroku?   It seems the steps will be slightly different

**Comment by srhoulam** [comment]
This list of steps may not be complete, but it contains the big ones:

1. Get a Heroku MongoLab instance.
2. Alter your code so that mongoose connects to it instead of localhost.
3. Alter your CORS allowed origins to include your deployed front-end on github pages.

**Comment by jrhorn424** [comment]
> We will be receiving instructions on how to setup our backend on Heuroku? It seems the steps will be slightly different

Slightly different from the docs? Slightly different than using rails? Not sure what you mean. If you mean different than rails: http://lmgtfy.com/?q=heroku+deploy+express&l=1 :stuck_out_tongue: 

In any case, to answer your question, we will not be providing instructions.
