### ISSUE TITLE
MATERIALIZED PATHS

### ISSUE THREAD

**Issue by kaylal12** [ga-wdi-boston/express-group-project#47]
Group: Edie, Jeff, Kayla

We are unsure of how to deal with materialized paths and dont know what to do. We understand at a high level how they work but are very unsure how to implement and utilize them in our code specifically.  We can upload a file in AWS, that shows up in localhost:3000/images, and in our mongo db (file-upload) but are lost from there.

In-person assistance to walk through this with us would be nice. (Antony?)
We will be in the dugout.

**Comment by jrhorn424** [comment]
After talking with @kaylal12, I believe this issue is resolved.

**Comment by kaylal12** [comment]
This is our new schema for files:

```var imageSchema = new mongoose.Schema({
  url: {
    type: String,
    required: true
  },
  path: {
    type: String,
    required: true
  }
});```

This is our aws upload file:

```
var awsUpload = function(buffer, caption) {

  var fileType = getFileType(buffer);

  if (!fileType) {
    fileType = {
      ext: 'bin',
      mime: 'application/octet-stream'
    };
  }

  var key = util.format('%s/%s.%s',
    (new Date()).toISOString().split('T')[0],
    crypto.pseudoRandomBytes(16).toString('hex'),
    fileType.ext);

  var params = {
    ACL: 'public-read',
    Bucket: bucket,
    Key: key,
    ContentType: fileType.mime,
    Body: buffer
  };

  return new Promise(function(resolve, reject) {
    awsS3.upload(params, function(err, data) {
      if (err) {
        reject(err);
      }
      resolve(data);
      console.log(data);
    });
  }).then(function(data) {
    return Image.create({
      url: data.Location,
      path: params.Key
    });
  });
};
```

When uploading a file through the command line, it is successful and shows this:
```
{ _id: 565fd41ed0ed4f50683c281b,
  path: '2015-12-03/ecfcca3ac8345b291c807bffadbdae95.jpg',
  url: 'https://midden-wd-09.s3.amazonaws.com/2015-12-03/ecfcca3ac8345b291c807bffadbdae95.jpg',
  __v: 0 }
```

We're not entirely sure how to add the username into the path string. We have tried to require the User model into the aws upload file but are not successful in pulling out a username. 
Should we be trying to do this within a different part of the project?

Also, is it okay to remove the  "(new Date()).toISOString().split('T')[0]" from the key?
