### ISSUE TITLE
Creating the path for materialized paths

### ISSUE THREAD

**Issue by kaylal12** [ga-wdi-boston/express-group-project#49]
This is our new schema for files:

```var imageSchema = new mongoose.Schema({ url: { type: String, required: true }, path: { type: String, required: true } });```

This is our aws upload file:

```
var awsUpload = function(buffer, caption) {

  var fileType = getFileType(buffer);

  if (!fileType) {
    fileType = {
      ext: 'bin',
      mime: 'application/octet-stream'
    };
  }

  var key = util.format('%s/%s.%s',
    (new Date()).toISOString().split('T')[0],
    crypto.pseudoRandomBytes(16).toString('hex'),
    fileType.ext);

  var params = {
    ACL: 'public-read',
    Bucket: bucket,
    Key: key,
    ContentType: fileType.mime,
    Body: buffer
  };

  return new Promise(function(resolve, reject) {
    awsS3.upload(params, function(err, data) {
      if (err) {
        reject(err);
      }
      resolve(data);
      console.log(data);
    });
  }).then(function(data) {
    return Image.create({
      url: data.Location,
      path: params.Key
    });
  });
};
```

When uploading a file through the command line, it is successful and shows this:

```
{ _id: 565fd41ed0ed4f50683c281b,
  path: '2015-12-03/ecfcca3ac8345b291c807bffadbdae95.jpg',
  url: 'https://midden-wd-09.s3.amazonaws.com/2015-12-03/ecfcca3ac8345b291c807bffadbdae95.jpg',
  __v: 0 }
```

We're not entirely sure how to add the username into the path string. We have tried to require the User model into the aws upload file but are not successful in pulling out a username. 
Should we be trying to do this within a different part of the project?

**Comment by raq929** [comment]
I'm not sure if this is the right answer, but when the user makes a request to the server, there will be a user object attached to it, so you can access it using req.user.username. So you can grab the username when they are sending the file.

**Comment by gaand** [comment]
What Rachel said.  Also, add `ownerId: { type: Schema.Types.ObjectId, ref: 'User' }` (or some such) to your imageSchema.

**Comment by kaylal12** [comment]
So the path we get when we create our image can stay like this:

```
{ _id: 565fd41ed0ed4f50683c281b,
  path: '2015-12-03/ecfcca3ac8345b291c807bffadbdae95.jpg',
  url: 'https://midden-wd-09.s3.amazonaws.com/2015-12-03/ecfcca3ac8345b291c807bffadbdae95.jpg',
  __v: 0 }
```

and then in other files (app.use? user routes?) we would be grabbing the username and attaching the file path to it, so that when we try to get a file the url would read url.com/username/filename or url.com/username/folder/filename?

When we create the image, what should be put within the promise when the Image.create is run? or does it just do it for us?

```
.then(function(data) {
    return Image.create({
      url: data.Location,
      path: params.Key
    });
```

**Comment by gaand** [comment]
You'll need to set `ownerId` (or whatever you're calling it) to the value of the user uploading the file.

**Comment by kaylal12** [comment]
Should we be setting that in a controller somewhere? Or should we be able to access the user within the aws upload file?

**Comment by gaand** [comment]
You probably want to pass it from the controller to the awsUpload function.

**Comment by kaylal12** [comment]
To clarify, in the controller, we should call the awsUpload function and pass it as an argument?

**Comment by gaand** [comment]
You can add additional arguments if you need to.  If this isn't clear I'll swing by.

**Comment by kaylal12** [comment]
Whenever you get the chance, that'd be great (we're in the dugout)

**Comment by kaylal12** [comment]
Added options as arguments in awsUpload function, will test and see how it goes.
