### ISSUE TITLE
need help with ajax register 

### ISSUE THREAD

**Issue by leahphuong** [ga-wdi-boston/express-group-project#5]
I got this error msg:

XMLHttpRequest cannot load http://localhost:3000/signup. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.

when I tried to register a user.

**Comment by srhoulam** [comment]
Looks like an actual CORS error.

**Comment by srhoulam** [comment]
You need to use the CORS module to make your back-end serve the necessary CORS headers to enable cross-origin requests. Here is a link to the repo and documentation. You can install it with `npm install cors --save`.

https://github.com/expressjs/cors
