### ISSUE TITLE
localhost:3000/whyDoesn'tThisRouteWork?

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/express-group-project#50]
Ok, here's my app.js:
`var blogRoute = require('./routes/blogRoute');`
and, as the last route:
`app.use('/:username', blogRoute);`

In blogRoute.js:
```javascript
var express = require('express');
var passport = require('passport');
var router = express.Router();
var blogController = require('../controllers/blogController');

router.get('/', function(req, res){ res.json({username: req.params});
});


module.exports = router;
```

This gives me `{"username":{}}`

When I move `function(req, res){ res.json({username: req.params});
}`
into the app.js file, like so:
```javascript
app.use('/:username', function(req, res){ res.json({username: req.params})});
```
I get back `{"username":{"username":"whateverIputAfterTheSlash"}}`, which I am currently using as a workaround.

Is there something I'm missing here? I feel like this should work in the route file.

**Comment by jrhorn424** [comment]
I think you have things inverted. Try this:

```
# app.js
app.use('/', blogRoute);
```

```
# routes/blog.js

router.get('/:username', function(req, res){ res.json({username: req.params});
});
```
