### ISSUE TITLE
select "pay" button in Stripe iframe?

### ISSUE THREAD

**Issue by kuramameng** [ga-wdi-boston/express-group-project#51]
Our group has incorporated Stripe payment form into our app, but since the pop-up form is iframe, we are having trouble selecting its "pay" button and add handler to it. This handler is crucial because after the form submitted, we need to make a createOrder call to the backend. 

Any assistance will be much appreciated!

**Comment by jrhorn424** [comment]
What does "having trouble" mean? Are you getting an error? Please provide more detail.

**Comment by jrhorn424** [comment]
Not sure whether this helps: http://stackoverflow.com/questions/364952/jquery-javascript-accessing-contents-of-an-iframe

**Comment by kuramameng** [comment]
Thanks for the article. it does provide some insight. 

Now when I do $('iframe'), it actually returns the whole iframe. However, when I try $('iframe').contents(), it gives out error message "Uncaught DOMException: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "http://localhost:5000" from accessing a cross-origin frame.(…)"

**Comment by kuramameng** [comment]
complete error message: 
Uncaught DOMException: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "http://localhost:5000" from accessing a cross-origin frame.
    at Error (native)
    at x.each.contents (http://localhost:5000/js/jquery.js:5:23105)
    at Function.x.extend.map (http://localhost:5000/js/jquery.js:4:6171)
    at x.fn.(anonymous function) [as contents] (http://localhost:5000/js/jquery.js:5:23219)
    at <anonymous>:2:13
    at Object.InjectedScript._evaluateOn (<anonymous>:875:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:808:34)
    at Object.InjectedScript.evaluate (<anonymous>:664:21)

**Comment by gaand** [comment]
I think you need to use a custom form.  You can look at https://github.com/Group-404 to see what a group from a previous cohort used.
