### ISSUE TITLE
Delete successfully deleting listItem object, but not the reference in User

### ISSUE THREAD

**Issue by dhuddell** [ga-wdi-boston/express-group-project#52]
We are successfully deleting the listItem by passing in an ObjectId and sending it to the db.listItem (etc).

I need help reaching the correct User (findByIdandUpdate) and then deleting($pull-ing ?) the array value that matches our listItem ObjectId. Can't get it working in mongo yet.

**Comment by dhuddell** [comment]
Amend: User looks like this: 
```
> db.users.find({ _id : ObjectId('565e0904eb8f76255c362e68')}).pretty()
{
	"_id" : ObjectId("565e0904eb8f76255c362e68"),
	"userName" : "a@a",
	"list" : [
		ObjectId("565f1c1f7eba031810ae2399"),
		ObjectId("565f1c257eba031810ae239a"),
		ObjectId("565f5436bee62b062befe125"),
		ObjectId("565f5521bee62b062befe126"),
		ObjectId("565f55fdbee62b062befe127"),
		ObjectId("565f5621bee62b062befe128"),
		ObjectId("565f585d33a946082ed3f0c6"),
		ObjectId("565f5a2ad85cafa82fac6b0e"),
		ObjectId("565f5b0f8f1d8726303752b6"),
		ObjectId("565f5b7e8f1d8726303752b7"),
		ObjectId("565f5fca372024dc325568f1"),
		ObjectId("565f60afc0524803347fb95f"),
		ObjectId("565f61a88f95d9743461426e")
	],
	"__v" : 13,
	"passwordDigest" : "$2a$16$vQhBjk7b8XLYv.5D9eslm.TVcPDiFKmfVez1jxu1U1G1sUne51/Oq"
}
```
This is what I was trying to use in Mongo, and the response (no change)
```
> db.users.update({ _id : ObjectId('565e0904eb8f76255c362e68')}, { $pull: { list: [ObjectId("565f61a88f95d9743461426e")] } })
WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 0 })
```
Also tried
```
> db.users.update({ _id : ObjectId('565e0904eb8f76255c362e68')}, { $pull: { list: ["565f61a88f95d9743461426e"] } })
WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 0 })
```

**Comment by dhuddell** [comment]
I'm going to close this issue bc we're going to prioritize update over getting this function of delete correct.

**Comment by dhuddell** [comment]
Reopening bc we finished update.

**Comment by srhoulam** [comment]
Dan, using the retrieved document, you can use array methods on its array attribute.

For removing an element from the beginning of the array, use the `shift` method. For removing a method from the end of the array, use the `pop` method. For removing an element from the middle, use the `splice` method after determining the index of the element to remove.

**Comment by dhuddell** [comment]
I won't have the array, I only have the ID. So I feel like it involved finding the element by it's value and then $pulling or splicing that way

**Comment by gaand** [comment]
Related.  When you get it working, delete from the list first then delete the item.

**Comment by gaand** [comment]
I think all you need is Model.findByIdAnd Update with `$pullAll` https://docs.mongodb.org/manual/reference/operator/update/pullAll/

**Comment by dhuddell** [comment]
I was planning to just remove the one list item, not the whole list.

**Comment by srhoulam** [comment]
Dan, I was talking about the document with the array of references in my comment. It's easier if you retrieve the document and save it after making changes than to use Mongo update operators.

**Comment by gaand** [comment]
`$pullAll` removes the items matched.

**Comment by dhuddell** [comment]
I apologize for misunderstanding you both. I'm going to close this issue, I'll use this in trying to solve the issue.
