### ISSUE TITLE
what are db and session definitions in heroku

### ISSUE THREAD

**Issue by mkutter72** [ga-wdi-boston/express-group-project#55]
in project 2 we need to switch to Puma,   can you give guidance on what to do for project 3?

on my backend I have the following definitions for running with local host

mongoose.connect("mongodb://localhost/project3-survey");

	store : new MongoStore({
		url : "mongodb://localhost/ga-passport-sessions"
	}),

**Comment by gaand** [comment]
You'll need to look at how you use mongodb on heroku. I suggest using the same mongodb instance for both the session and survey data.

**Comment by srhoulam** [comment]
Mike, you need to set the URL to your MongoLabs instance URL.

**Comment by srhoulam** [comment]
Any progress, Mike?

**Comment by mkutter72** [comment]
Saad,  I slacked you a question

**Comment by srhoulam** [comment]
Please put it here so that you can potentially get help from anyone on the instructional team.

**Comment by mkutter72** [comment]
I seem to have a circular dependency is setting up Heurko.  It wants me to run installing Mongo lab on an established project but I don't want to push my project until I have the database URL coded correctly

**Comment by mkutter72** [comment]
I Tried installing Mongo lab and got the following:
heroku addons:create mongolab
 !    Please verify your account to install this add-on plan (please enter a credit card) For more information, see https://devcenter.heroku.com/categories/billing Verify now at https://heroku.com/verify 
~/WebProjects/Project3/project3-backend (mjk-heroku)$

**Comment by srhoulam** [comment]
Yes, they do want you to put a credit card on file. You can get the free MongoLab plan where it shuts down when you reach the usage limit, so you won't necessarily be charged any money.

**Comment by mkutter72** [comment]
can I please get some help in thinking about how to configure my backend so I can run it both in Heroku and locally?

**Comment by gaand** [comment]
Can you use environment variables?
