### ISSUE TITLE
req.body vs req.params in updating a Poll functionality

### ISSUE THREAD

**Issue by baz1389** [ga-wdi-boston/express-group-project#56]
With the code below, we can hard code a title to update the poll we specify. However, we have tried many iterations of req/res.body/params.title etc and still can't figure out what needs to go where the 'NEW TITLE HERE" text is

```
var update = function (req, res, next) {
  console.log("here are update params: " + req.params.id);
  console.log("log of req.body.title: " + req.body.title);
  Poll.findOneAndUpdate({"_id": req.params.id}, {$set: {title: "NEW TITLE HERE"}}, {new: true}).exec()
  .then(function(poll) {
    console.log("This poll is being returned: " + poll);
    res.json(poll);
  })
  .catch(function(error){
    next(error);
  });
};

```

**Comment by srhoulam** [comment]
Attributes of `req.params` refer to route parameters. If your route path is `/resource/:id`, and a request is sent to `/resource/123`, then `req.params.id` for that request will be `'123'` (note: it's a string).

Attributes of `req.body` refer to values passed in the body. For example, when you make your login request, and send an object as the request data, you can think of that object as being assigned to `req.body` for that request.

**Comment by baz1389** [comment]
when we console log  req.body.title and req.params.title they both return undefined. Not quite sure what to do...

**Comment by srhoulam** [comment]
What is the route for this handler?

**Comment by baz1389** [comment]
```
router.patch('/:id', pollCtrl.update);
```

**Comment by srhoulam** [comment]
Log `req.params.id`

**Comment by baz1389** [comment]
```
here are update params: 565f0a753cc192af11e897ba
```

**Comment by srhoulam** [comment]
The object containing the `title` attribute was assigned to the `poll` attribute of a wrapping object.
