### ISSUE TITLE
Delete User reference + listItem throwing 500

### ISSUE THREAD

**Issue by dhuddell** [ga-wdi-boston/express-group-project#59]
I think the $pullAll is throwing the error, and I don't understand why .. 
`$pullAll : { list: [ ObjectId(req.params.id) ] }`

**Comment by dhuddell** [comment]
To update this, I don't know how to test this command in Mongo.. which is why I'm not sure if it's working at all at the moment.

**Comment by gaand** [comment]
You need to test in node.

**Comment by gaand** [comment]
Does jshint say anything useful?

**Comment by gaand** [comment]
You may need to:
```js
var mongoose = require('mongoose');
var ObjectId = mongoose.Schema.Types.ObjectId;
```

**Comment by dhuddell** [comment]
back in here if you're available anytime soon.
