### ISSUE TITLE
http: issue

### ISSUE THREAD

**Issue by kaylal12** [ga-wdi-boston/express-group-project#60]
Our coors error has turned into a 500 error.  We've checked the routes and I put in a debugger to see if I could find an issue.

POST http://localhost:3000/login 500 (Internal Server Error)
ajax.js:22 Object {jqxher: Object, status: "error", error: "Internal Server Error"}callback @ ajax.js:22cb @ ajax.js:40(anonymous function) @ api.js:8j @ jquery.js:2k.fireWith @ jquery.js:2x @ jquery.js:4b @ jquery.js:4
jquery.js:4 POST http://localhost:3000/images 404 (Not Found)send @ jquery.js:4m.extend.ajax @ jquery.js:4(anonymous function) @ upload.js:7m.event.dispatch @ jquery.js:3r.handle @ jquery.js:3
upload.js:16 Object {readyState: 4, responseText: "<!DOCTYPE html>↵<html>↵  <head>↵    <title></title…are/initialize.js:53:5)</pre>↵↵  </body>↵</html>↵", status: 404, statusText: "Not Found"}(anonymous function) @ upload.js:16j @ jquery.js:2k.fireWith @ jquery.js:2x @ jquery.js:4b @ jquery.js:4

**Comment by gaand** [comment]
This is on the server.  Are you getting any errors from the express?

**Comment by gaand** [comment]
If not, would you please change the line
```js
if (app.get('env') === 'development') {
```
to
```js
if (true || app.get('env') === 'development') {
```
and restart express.

**Comment by eshimel** [comment]
Jeff here: we updated the app.js with your new code, and then started the express server with DEBUG=packRat-backend2:* npm start to try and goad an error.  Login now works but we are getting that 500 error on file upload.  What we got in the console is below:

```
^C~/Documents/WDI/Midden/packRat-backend2 (uploading)$ DEBUG=packRat-backend2:* npm start

> packRat-backend@0.0.0 start /Users/BuddySystem/Documents/WDI/Midden/packRat-backend2
> node ./bin/www

OPTIONS /login 204 3.678 ms - -
POST /login 200 5362.219 ms - 2
POST /login 200 5596.616 ms - 2
POST /images 500 161.529 ms - 1717
```
