### ISSUE TITLE
Unable to write HTML/CSS

### ISSUE THREAD

**Issue by TeoPaolucci** [ga-wdi-boston/express-group-project#61]
I have a functional back-end for what I need so far and I know how to write an api and javascript files for my front end so that it can interact with my back end, but I have no idea how to go about setting up my webpage. It isn't so much a lack of my knowledge of HTML/CSS but rather simply not knowing what to do. The best I can do is identical to what I had for project 2, a shell of a webpage good for testing the api and backend, but thats about it. I don't know what to do and I need help.

**Comment by srhoulam** [comment]
You will need these articles to move forward from where we left off:

https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener
https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onhashchange
http://handlebarsjs.com/

**Comment by srhoulam** [comment]
`location.hash` is where you find the current URL hash.

**Comment by srhoulam** [comment]
You seem quite able to write your front-end HTML and CSS now.
