### ISSUE TITLE
Cannot delete file from MongoDB

### ISSUE THREAD

**Issue by jcmeyer10** [ga-wdi-boston/express-group-project#67]
We are trying to delete a file from MongoDB and AWS S3.  We are having trouble finding a single file.  We get a success in the console but nothing happens in the DB.  

On the front end:
Here is our API call  

```delete: function(callback) {
    this.ajax({
      method: 'DELETE',
      url: this.url + '/images',
      contentType: 'application/json',
      // data: JSON.stringify(image)
    }, callback);
  },```

Here is our click handler
```
$('#delete').on('submit', function(e) {
    var image = form2object(this);
        var cb = function cb(error, data) {
          if (error) {
            callback(error);
            return;
          }
          callback(null, data);
          console.log('success');
        };
        e.preventDefault();
        packrat.delete(cb);
  });```

ON the back end here is the controller for image
```
var destroy = function destroy(req, res, next){
  var id = req.get("id");
  Image.remove({ "_id": id }, function (err, image) {
    console.log("deleting single image");
      if (err) {
        return next(err);
    } else {
        res.json(image);
      }
  });```

**Comment by gaand** [comment]
I think you want `findByIdAndRemove`

**Comment by jcmeyer10** [comment]
```
var id = req.get("id");
Image.findByIdAndRemove({ "_id": id }, function (err, image) {console.log("deleting single image");
if (err) {
return next(err);
} else {
res.json(image);
}
});```

We changed it in the var destroy but it looks like {"_id" : ObjectId("xxxxxxxxxxxxxxxxxxxxxxxx").  Are we not accessing it the right way?

**Comment by jcmeyer10** [comment]
when we see it in the mongodb database

**Comment by gaand** [comment]
```js
Image.findByIdAndRemove(id, ...
```

**Comment by jcmeyer10** [comment]
Cool thank you!

**Comment by jcmeyer10** [comment]
Got it figured out and have full CRUD
