### ISSUE TITLE
Error - detached head

### ISSUE THREAD

**Issue by LaurisaNeuwirth** [ga-wdi-boston/express-group-project#7]
I am trying to pull from remote to update my local repo and git is giving me the following error: "Aborting
could not detach HEAD".

I am on my local development branch and had typed in: git pull origin development

**Comment by tdyer** [comment]
did you google this error?

**Comment by LaurisaNeuwirth** [comment]
yes it references the need for a rebase but I don't want to make a mistake with it.

**Comment by LaurisaNeuwirth** [comment]
I am confused by the references.

**Comment by tdyer** [comment]
Problem was that the .gitignore didn't exclude the node_modules directory.
