### ISSUE TITLE
mongoose modules test

### ISSUE THREAD

**Issue by gracenjambi** [ga-wdi-boston/express-group-project#8]
We have written our first test file, and when testing our modules we persistently get the error below:

"ReferenceError: require is not defined at test/create_user.js:1:16 Error: error loading js file: test/create_user.js"

Our script: 
var mongoose = require("mongoose");
var User = require("../models/index")

User.create(
  {
    userName: 'Henry',
    passwordDigest: "Rollins"
  });

**Comment by gaand** [comment]
How are you running this script?

**Comment by gracenjambi** [comment]
We are using Mongo shell

**Comment by gracenjambi** [comment]
Do we have to use Node?

**Comment by srhoulam** [comment]
Yes, the code you pasted above should be run in node.

**Comment by srhoulam** [comment]
Helped with retrieving models from Mongoose.
