### ISSUE TITLE
Deleting users

### ISSUE THREAD

**Issue by sarabrentmccoy** [ga-wdi-boston/express-group-project#9]
Group: Sarabrent, Meng, Dave (berners-lee)

When we try to test our destroy function using Postman, we get a 404 error. 

We're a little bit confused about the DELETE syntax in Express; the function works when we use GET method but not when we use DELETE.

**Comment by gaand** [comment]
What's the path?  Are you including an id (long hex string) at the end?

**Comment by sarabrentmccoy** [comment]
We're trying to use userName as the identifier to delete the profile.

The path is /destroy and the method is DELETE.

**Comment by gaand** [comment]
What's the route that's supposed to handle that?

**Comment by sarabrentmccoy** [comment]
router.route('/destroy').
 get(authCtrl.destroy.delete);

**Comment by srhoulam** [comment]
Can you also paste here the code for `authCtrl.destroy.delete`?

**Comment by gaand** [comment]
Did you add a destroy property to authCtrl?  What's in that?  Is it supposed to destroy the the logged in user?

**Comment by sarabrentmccoy** [comment]
Yes. Do we need to log the user out first? 

Here's the code, @srhoulam 

destroy : {
       delete : function(req, res) {
           var db = req.db;
           db.users.remove({"userName":req.user.userName}, function(err, docs) {
               if (err) return err;
               res.send(docs); // see results
           });
       }
   }

**Comment by gaand** [comment]
What's the code the code that invokes destroy?  I think you have a method mismatch.

**Comment by gaand** [comment]
I just reread you question.  It doesn't work with delete because you defined it for get, not delete

router.route('/destroy').
**delete**(authCtrl.destroy.delete);

**Comment by gaand** [comment]
On a separate issue, you probably don't want to delete users in the auth route.

**Comment by sarabrentmccoy** [comment]
There was an syntax error of inconsistency: We were using both req.users and req.user. Thanks!
